#!/bin/bash

set -eou pipefail

# Make menu selections in one column
COLUMNS=12

# List local branches.
IFS=$'\n' read -r -d '' -a BRANCHES < <( git branch && printf '\0' )

# Add exit option.
EXIT=EXIT
BRANCHES+=("$EXIT")

# Prompt the user to select one of the available branches.
echo "Select branch:"
select SELECTED_BRANCH in "${BRANCHES[@]}"; do

    if [ "$SELECTED_BRANCH" = "$EXIT" ]; then
        exit
    fi

    [[ -n $SELECTED_BRANCH ]] || { echo "Invalid branch! Try again." >&2; continue; }
    break

done

# Remove selection mark (*).
UNMARKED_BRANCH=${SELECTED_BRANCH//\*/}

# Remove trailing spaces.
BRANCH=$(echo "$UNMARKED_BRANCH" | xargs)

# Checkout selected branch.
git checkout "$BRANCH"
